void customSetup(){
    pinmode(RED_BUTTON_PIN, INPUT_PULLUP);
    pinmode(BLUE_BUTTON_PIN, INPUT_PULLUP);
    pinmode(GREEN_BUTTON_PIN, INPUT_PULLUP);
    pinmode(BLACK_BUTTON_PIN, INPUT_PULLUP);
    pinmode(WHITE_BUTTON_PIN, INPUT_PULLUP);
    pinmode(YELLOW_BUTTON_PIN, INPUT_PULLUP);
    pinmode(GREY_BUTTON_PIN, INPUT_PULLUP);
    pinmode(KEY_BUTTON_PIN, INPUT_PULLUP);
    pinmode(CAP_BUTTON_PIN, INPUT_PULLUP);
    pinmode(CAP_LED_PIN, OUTPUT);
    pinmode(RED_LED_PIN, OUTPUT);
}