void customSetup(){
    pinMode(RED_BUTTON_PIN, INPUT_PULLUP);
    pinMode(BLUE_BUTTON_PIN, INPUT_PULLUP);
    pinMode(GREEN_BUTTON_PIN, INPUT_PULLUP);
    pinMode(BLACK_BUTTON_PIN, INPUT_PULLUP);
    pinMode(WHITE_BUTTON_PIN, INPUT_PULLUP);
    pinMode(YELLOW_BUTTON_PIN, INPUT_PULLUP);
    pinMode(GREY_BUTTON_PIN, INPUT_PULLUP);
    pinMode(KEY_BUTTON_PIN, INPUT_PULLUP);
    pinMode(CAP_BUTTON_PIN, INPUT_PULLUP);
    pinMode(CAP_LED_PIN, OUTPUT);
    pinMode(RED_LED_PIN, OUTPUT);
}